### ISSUE TITLE
Can't build dockerpatch

### ISSUE THREAD

**Issue by thedrow** [moul/dockerpatch#1]
I'm getting `/dockerpatch.go:34: not enough arguments in call to parser.Parse`.
Any idea why?

**Comment by michaelhood** [comment]
@thedrow I just opened a PR to fix it - #2

**Comment by moul** [comment]
#2 is merge, @thedrow can you give a new try?

**Comment by thedrow** [comment]
Looks like it works thanks.
It'd be nice if you could provide binaries though so we wouldn't have to go through with compiling the CLI.

**Comment by moul** [comment]
Just added an homebrew script, you should be able to run `brew install moul/moul/dockerpatch` (at least on OS X)
